services:
  minio:
    image: docker.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: curl -fLI http://localhost:9000/minio/health/live
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio-data:/data
    networks:
      - file-storage
  
  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    entrypoint: [
      "/bin/sh", 
      "-c", 
      "mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; mc mb local/$${MINIO_BUCKET_NAME} --ignore-existing;"
    ]
    networks:
      - file-storage
  file-upload-postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-upload_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-upload_pass}
      POSTGRES_DB: ${POSTGRES_DB:-upload_db}
    ports:
      - "5437:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - file-storage
  file-upload-backend:
    image: ghcr.io/claytonmuhoza/spring-s3-upload-backend:main
    container_name: spring-backend
    depends_on:
      minio-init:
        condition: service_completed_successfully
      file-upload-postgres:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-S3}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-upload_db}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-upload_user}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-upload_pass}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8085:8080"
    networks:
      - file-storage

  file-upload-frontend:
    image: ghcr.io/ton-nom-utilisateur-github/spring-s3-upload-frontend:main
    container_name: angular-frontend
    depends_on:
      - file-upload-backend
    ports:
      - "8090:80"
    networks:
      - file-storage


volumes:
  minio-data:

networks:
  file-storage: