name: Build Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'fileupload-frontend/**'
      - '.github/workflows/build-frontend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: claytonmuhoza/spring-s3-upload-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./fileupload-frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}